/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paket.TugasAkhir;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Microsoft
 */
public class FormMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuUtama
     */
    public FormMenuUtama() {
        initComponents();
        CenterForm();
    }
    
    private void CenterForm(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuLogin = new javax.swing.JMenu();
        JMenuMasuk = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        JMenuData = new javax.swing.JMenu();
        JMenuDataBarang = new javax.swing.JMenuItem();
        JMenuDataPembelian = new javax.swing.JMenuItem();
        JMenuDataPenjualan = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        JMenuBantuan = new javax.swing.JMenu();
        BantuanBarang = new javax.swing.JMenuItem();
        BantuanBeli = new javax.swing.JMenuItem();
        BantuanJual = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Marker", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Jalan Sri Bungur Tanjung Bintang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Marker", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Marker", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Lampung Selatan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Marker", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Lampung");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Marker", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("35361");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Microsoft\\Pictures\\PicsArt_01-17-08.54.49.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 400, -1));

        MenuLogin.setText("Akun");

        JMenuMasuk.setText("Keluar");
        JMenuMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuMasukActionPerformed(evt);
            }
        });
        MenuLogin.add(JMenuMasuk);
        MenuLogin.add(jSeparator1);

        jMenuBar1.add(MenuLogin);

        JMenuData.setText("Data");

        JMenuDataBarang.setText("Data Barang");
        JMenuDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuDataBarangMouseClicked(evt);
            }
        });
        JMenuDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuDataBarangActionPerformed(evt);
            }
        });
        JMenuData.add(JMenuDataBarang);

        JMenuDataPembelian.setText("Data Pembelian");
        JMenuDataPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuDataPembelianActionPerformed(evt);
            }
        });
        JMenuData.add(JMenuDataPembelian);

        JMenuDataPenjualan.setText("Data Penjualan");
        JMenuDataPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuDataPenjualanActionPerformed(evt);
            }
        });
        JMenuData.add(JMenuDataPenjualan);
        JMenuData.add(jSeparator3);

        jMenuBar1.add(JMenuData);

        JMenuBantuan.setText("Bantuan");
        JMenuBantuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuBantuanMouseClicked(evt);
            }
        });
        JMenuBantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuBantuanActionPerformed(evt);
            }
        });

        BantuanBarang.setText("Form Barang");
        BantuanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BantuanBarangActionPerformed(evt);
            }
        });
        JMenuBantuan.add(BantuanBarang);

        BantuanBeli.setText("Form Pembelian");
        BantuanBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BantuanBeliActionPerformed(evt);
            }
        });
        JMenuBantuan.add(BantuanBeli);

        BantuanJual.setText("Form Penjualan");
        BantuanJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BantuanJualActionPerformed(evt);
            }
        });
        JMenuBantuan.add(BantuanJual);
        JMenuBantuan.add(jSeparator2);

        jMenuBar1.add(JMenuBantuan);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 546, 454);
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuDataBarangActionPerformed
        // TODO add your handling code here:
        FormBarang fb = new FormBarang();
        fb.setVisible(true);
    }//GEN-LAST:event_JMenuDataBarangActionPerformed

    private void JMenuMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuMasukActionPerformed

    private void JMenuDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuDataBarangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuDataBarangMouseClicked

    private void JMenuDataPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuDataPembelianActionPerformed
        // TODO add your handling code here:
        FormDataPembelian fb = new FormDataPembelian();
        fb.setVisible(true);
    }//GEN-LAST:event_JMenuDataPembelianActionPerformed

    private void JMenuDataPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuDataPenjualanActionPerformed
        // TODO add your handling code here:
        FormDataPenjualan fb = new FormDataPenjualan();
        fb.setVisible(true);
    }//GEN-LAST:event_JMenuDataPenjualanActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void JMenuBantuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuBantuanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuBantuanMouseClicked

    private void JMenuBantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuBantuanActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_JMenuBantuanActionPerformed

    private void BantuanJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BantuanJualActionPerformed
        // TODO add your handling code here:
        BantuanPenjualan bantuanjual = new BantuanPenjualan();
        bantuanjual.setVisible(true);
    }//GEN-LAST:event_BantuanJualActionPerformed

    private void BantuanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BantuanBarangActionPerformed
        // TODO add your handling code here:
        BantuanBarang bantuan = new BantuanBarang();
        bantuan.setVisible(true);
    }//GEN-LAST:event_BantuanBarangActionPerformed

    private void BantuanBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BantuanBeliActionPerformed
        // TODO add your handling code here:
        BantuanPembelian bantuanbeli = new BantuanPembelian();
        bantuanbeli.setVisible(true);
    }//GEN-LAST:event_BantuanBeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BantuanBarang;
    private javax.swing.JMenuItem BantuanBeli;
    private javax.swing.JMenuItem BantuanJual;
    private javax.swing.JMenu JMenuBantuan;
    public javax.swing.JMenu JMenuData;
    private javax.swing.JMenuItem JMenuDataBarang;
    private javax.swing.JMenuItem JMenuDataPembelian;
    private javax.swing.JMenuItem JMenuDataPenjualan;
    private javax.swing.JMenuItem JMenuMasuk;
    private javax.swing.JMenu MenuLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables

    private void FormLogin() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void set(float CENTER_ALIGNMENT) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
