/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paket.TugasAkhir;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Microsoft
 */
public class FormLogin extends javax.swing.JFrame {

    TugasAkhir Merlinda = new TugasAkhir();

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        JT_IDPengguna.setText("");
        JT_KataSandi.setText("");
        CenterForm();
    }

    void menuBarTrue() {

    }

    public void Login() {
        Merlinda.PBOTugasAkhir();
        try {
            ResultSet result = Merlinda.state.executeQuery("SELECT * FROM tbl_pengguna "
                    + "where IDPengguna = '" + JT_IDPengguna.getText() + "' "
                    + "and KataSandi='" + JT_KataSandi.getText() + "' ");
            if (result.next()) {
                if ((result.getString("IDPengguna")).equals("Admin")) {
                    FormMenuUtama x = new FormMenuUtama();
                    x.setVisible(true);
                    x.JMenuData.setVisible(true);
                } else {
                    FormMenuUtama x = new FormMenuUtama();
                    x.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Pengguna Tidak Terdaftar !!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error !!" + e);
        }
    }

    private void CenterForm() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JT_IDPengguna = new javax.swing.JTextField();
        Btn_MasukLogin = new javax.swing.JButton();
        Btn_BatalLogin = new javax.swing.JButton();
        JT_KataSandi = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Marker", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Marker", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Kata Sandi  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, 30));

        jLabel3.setFont(new java.awt.Font("Segoe Marker", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("ID Pengguna  :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        JT_IDPengguna.setFont(new java.awt.Font("Segoe Marker", 0, 14)); // NOI18N
        getContentPane().add(JT_IDPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, 30));

        Btn_MasukLogin.setFont(new java.awt.Font("Segoe Marker", 0, 14)); // NOI18N
        Btn_MasukLogin.setText("Masuk");
        Btn_MasukLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MasukLoginActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_MasukLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 70, -1));

        Btn_BatalLogin.setFont(new java.awt.Font("Segoe Marker", 0, 14)); // NOI18N
        Btn_BatalLogin.setText("Batal");
        Btn_BatalLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BatalLoginActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_BatalLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 70, -1));

        JT_KataSandi.setFont(new java.awt.Font("Segoe Marker", 0, 14)); // NOI18N
        getContentPane().add(JT_KataSandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 150, 30));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 20, 190));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 260, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_MasukLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MasukLoginActionPerformed
        // TODO add your handling code here:
        Login();
        dispose();
    }//GEN-LAST:event_Btn_MasukLoginActionPerformed

    private void Btn_BatalLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BatalLoginActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Btn_BatalLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_BatalLogin;
    private javax.swing.JButton Btn_MasukLogin;
    private javax.swing.JTextField JT_IDPengguna;
    private javax.swing.JPasswordField JT_KataSandi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
